import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Read canister IDs from the .env file generated by dfx
function getCanisterEnv() {
  const envVars = {};
  try {
    const envFile = readFileSync(join(__dirname, "../../.env"), "utf-8");
    for (const line of envFile.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const [key, ...rest] = trimmed.split("=");
      if (key) {
        envVars[key] = rest.join("=").replace(/^['"]|['"]$/g, "");
      }
    }
  } catch (e) {
    console.warn("Could not read .env file:", e.message);
  }
  return envVars;
}

const envVars = getCanisterEnv();

export default defineConfig({
  plugins: [react()],
  server: {
    proxy: {
      "/api": {
        target: "http://127.0.0.1:4943",
        changeOrigin: true,
      },
    },
  },
  build: {
    target: "es2020",
  },
  resolve: {
    dedupe: [
      "@dfinity/agent",
      "@dfinity/principal",
      "@dfinity/candid",
      "@dfinity/auth-client",
    ],
  },
  optimizeDeps: {
    include: [
      "simple-cbor",
      "buffer",
      "process",
      "@noble/curves/bls12-381",
    ],
  },
  define: {
    global: "globalThis",
    "process.env": JSON.stringify(envVars),
  },
});
